### ISSUE TITLE
gatsby build fails while generating thumbnails.

### ISSUE THREAD

**Issue by githubber** [gillkyle/sol-journal#19]
Hi,
I was really hoping to use this with Firebase, but it just won't build, getting stuck on thumbnail generation. I found some issue with this on other projects. 
Is there a specific npm or node version it needs? I began my 12 hours of attempts using node - v 13, but there were so many missing requirements and stuff, so I downgraded to node -v 8.10, and then I could at least start seeing `npm install` complete.  Anyway, this looks like it would be a great thing, but it just won't install nor build completely on my Mac. 

````
home:sol-journal home$ gatsby develop
success open and validate gatsby-configs - 0.112s
success load plugins - 0.796s
success onPreInit - 0.003s
success initialize cache - 0.020s
success copy gatsby files - 0.072s
success onPreBootstrap - 2.938s
success createSchemaCustomization - 0.028s
success source and transform nodes - 0.170s
success building schema - 0.353s
success createPages - 0.002s
success createPagesStatefully - 0.102s
success onPreExtractQueries - 0.002s
success update schema - 0.034s
success extract queries from components - 0.273s
success write out requires - 0.043s
success write out redirect data - 0.012s
success Build manifest and related icons - 0.119s
success onPostBootstrap - 0.144s
⠀
info bootstrap finished - 8.172 s
⠀
[                            ]   0.037 s 0/9 0% run queries
[                            ]   0.011 s 0/3 0% Generating image thumbnails

 ERROR 

UNHANDLED REJECTION { err:
   { Error
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
     code: 'ENOENT',
     errno: 'ENOENT',
     syscall: 'spawn /Users/ulken/sol-journal/node_modules/pngquant-bin/vendor/pngquant',
     path: '/Users/ulken/sol-journal/node_modules/pngquant-bin/vendor/pngquant',
     spawnargs: [ '-', '--quality', '50-75', '--speed', 4, '--strip' ],
     stdout: <Buffer >,
     stderr: <Buffer >,
     failed: true,
     signal: null,
     cmd: '/Users/ulken/sol-journal/node_modules/pngquant-bin/vendor/pngquant - --quality 50-75 --speed 4 --strip',
     timedOut: false,
     killed: false },
  message: 'Failed to process image /Users/ulken/sol-journal/src/img/landing-graphic-light.png' }



  Error: { err: 
     { Error
  
  - child_process.js:190 Process.ChildProcess._handle.onexit
    internal/child_process.js:190:19
  
  - child_process.js:372 onErrorNT
    internal/child_process.js:372:16
  
  - next_tick.js:138 _combinedTickCallback
    internal/process/next_tick.js:138:11
  
  - next_tick.js:180 process._tickCallback
    internal/process/next_tick.js:180:9
  
  - code: 'ENOENT',
  
  - errno: 'ENOENT',
  
  - syscall: 'spawn /Users/ulken/sol-journal/node_modules/pngquant-bin/vendor/pngquant',
  
  - path: '/Users/ulken/sol-journal/node_modules/pngquant-bin/vendor/pngquant',
  
  - spawnargs: [ '-', '--quality', '50-75', '--speed', 4, '--strip' ],
  
  - stdout: <Buffer >,
  
  - stderr: <Buffer >,
  
  - failed: true,
  
  - signal: null,
  
  - cmd: '/Users/ulken/sol-journal/node_modules/pngquant-bin/vendor/pngquant - --quality 50-75 --speed 4 --strip',
  
  - timedOut: false,
  
  - killed: false },
  
  - message: 'Failed to process image /Users/ulken/sol-journal/src/img/landing-graphic-light.png' }
  
  - index.js:115 process.on.reason
    [lib]/[gatsby-cli]/lib/index.js:115:14
  
  - index.js:155 processEmit
    [lib]/[gatsby-cli]/[signal-exit]/index.js:155:32
  
  - index.js:155 processEmit [as emit]
    [sol-journal]/[signal-exit]/index.js:155:32
  
  - promises.js:108 emitPendingUnhandledRejections
    internal/process/promises.js:108:22
  
  - next_tick.js:189 process._tickCallback
    internal/process/next_tick.js:189:7
  



[                            ]   0.037 s 0/9 0% run queries
[                            ]   0.011 s 0/3 0% Generating image thumbnails
````

**Comment by gillkyle** [comment]
Hmmm, I wonder if it might be a node issue, I'm on Node.js v11.15.0 locally (also on Mac) and things work okay on my machine and get deployed to Netlify okay where it builds alright. Maybe deploying it to Netlify where the environment is different would work?

**Comment by githubber** [comment]
I downgraded, but now I'm getting other errors, mostly about core-js. Seems there are conflicts or something about the older core-js that this project requires. Anyways, I can't get it to build, giving up.

**Comment by smamudhan** [comment]
I use firebase for my deployment of the app. I build and deploy using Gitlab CI. Would you like me to post the CI script here?
